export { default as LoginPage } from './LoginPage'
export { default as Register } from './Register'
export { default as BoardList } from './BoardList'
export { default as BoardDetail } from './BoardDetail'
export { default as BoardWrite } from './BoardWrite'